name: bola_negra
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  admob_widgets: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.13
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^3.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  generate: true
